apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "24"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"social-media-app"},"name":"social-media-app","namespace":"default"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"social-media-app"}},"template":{"metadata":{"labels":{"app":"social-media-app"}},"spec":{"containers":[{"env":[{"name":"DB_HOST","value":"mysql.default.svc.cluster.local"},{"name":"DB_PORT","value":"3306"},{"name":"DB_USER","value":"root"},{"name":"DB_PASSWORD","value":"rootpassword"},{"name":"DB_NAME","value":"social_media_app"},{"name":"REDIS_HOST","value":"redis"},{"name":"REDIS_PORT","value":"6379"}],"image":"social-media-app:v0.0.2","livenessProbe":{"httpGet":{"path":"/health","port":8080},"initialDelaySeconds":10,"periodSeconds":30},"name":"social-media-app","ports":[{"containerPort":8080}],"readinessProbe":{"httpGet":{"path":"/health","port":8080},"initialDelaySeconds":5,"periodSeconds":10},"resources":{"limits":{"cpu":"500m","memory":"256Mi"},"requests":{"cpu":"250m","memory":"64Mi"}}}],"restartPolicy":"Always"}}}}
  creationTimestamp: "2025-03-01T21:09:48Z"
  generation: 24
  labels:
    app: social-media-app
  name: social-media-app
  namespace: default
  resourceVersion: "1252506"
  uid: 24ca2520-4dd9-46f7-9421-f1cea4c9e491
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: social-media-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-03-02T04:25:19+05:30"
      creationTimestamp: null
      labels:
        app: social-media-app
    spec:
      containers:
        - env:
            - name: DB_HOST
              value: mysql.default.svc.cluster.local
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: root
            - name: DB_PASSWORD
              value: rootpassword
            - name: DB_NAME
              value: social_media_app
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
          image: docker.io/library/social-media-app:v1.0.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /apis/v1/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 3
          name: social-media-app
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /apis/v1/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 3
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 250m
              memory: 64Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 2
  conditions:
    - lastTransitionTime: "2025-03-01T22:58:31Z"
      lastUpdateTime: "2025-03-01T22:58:31Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2025-03-01T22:24:31Z"
      lastUpdateTime: "2025-03-01T22:58:31Z"
      message: ReplicaSet "social-media-app-69b8b67495" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
  observedGeneration: 24
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
