apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "109"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"social-media-app"},"name":"social-media-app","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"social-media-app"}},"template":{"metadata":{"labels":{"app":"social-media-app"}},"spec":{"containers":[{"env":[{"name":"DB_WRITE_HOST","value":"mysql-primary.mysql-replication.svc.cluster.local"},{"name":"DB_READ_HOST","value":"mysql-secondary.mysql-replication.svc.cluster.local"},{"name":"DB_PORT","value":"3306"},{"name":"DB_USER","value":"root"},{"name":"DB_PASSWORD","valueFrom":{"secretKeyRef":{"key":"mysql-root-password","name":"mysql"}}},{"name":"DB_NAME","value":"social_media_app"},{"name":"REDIS_HOST","value":"redis"},{"name":"REDIS_PORT","value":"6379"}],"image":"docker.io/library/social-media-app:20250306-230545","livenessProbe":{"httpGet":{"path":"/apis/v1/health","port":8080},"initialDelaySeconds":10,"periodSeconds":30},"name":"social-media-app","ports":[{"containerPort":8080}],"readinessProbe":{"httpGet":{"path":"/apis/v1/health","port":8080},"initialDelaySeconds":5,"periodSeconds":10},"resources":{"limits":{"cpu":"500m","memory":"256Mi"},"requests":{"cpu":"250m","memory":"64Mi"}},"volumeMounts":[{"mountPath":"/etc/db-secrets","name":"db-secrets","readOnly":true}]}],"volumes":[{"name":"db-secrets","secret":{"secretName":"mysql"}}]}}}}
  creationTimestamp: "2025-03-06T17:34:49Z"
  generation: 211
  labels:
    app: social-media-app
  name: social-media-app
  namespace: default
  resourceVersion: "176856"
  uid: b5923aeb-2c0d-4ea7-a110-2cfb45841e4d
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: social-media-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-03-25T13:14:18+05:30"
      creationTimestamp: null
      labels:
        app: social-media-app
    spec:
      containers:
        - env:
            - name: DB_WRITE_HOST
              value: mysql-primary.mysql-replication.svc.cluster.local
            - name: DB_READ_HOST
              value: mysql-secondary.mysql-replication.svc.cluster.local
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: root
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MYSQL_ROOT_PASSWORD
                  name: mysql-secret
            - name: DB_NAME
              value: social_media_app
            - name: REDIS_HOST
              value: redis-master.default.svc.cluster.local
            - name: REDIS_PORT
              value: "6379"
          image: docker.io/library/social-media-app:20250325-131357
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /apis/v1/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
          name: social-media-app
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 6060
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /apis/v1/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 250m
              memory: 64Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/db-secrets
              name: db-secrets
              readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: db-secrets
          secret:
            defaultMode: 420
            secretName: mysql-secret
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: "2025-03-25T07:44:28Z"
      lastUpdateTime: "2025-03-25T07:44:28Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2025-03-18T05:54:34Z"
      lastUpdateTime: "2025-03-25T07:44:28Z"
      message: ReplicaSet "social-media-app-7dbb7cf8fb" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
  observedGeneration: 211
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
