apiVersion: v1
kind: Service
metadata:
  name: social-media-app-service-pprof
spec:
  selector:
    app: social-media-app
  ports:
    - protocol: TCP
      port: 6060
      targetPort: 6060
  type: ClusterIP
