apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }

    stream {
        upstream mysql_backends {
            least_conn;
            server mysql-primary:3306;
            server mysql-replica:3306;
        }
        
        server {
            listen 3306;
            proxy_pass mysql_backends;
        }
    }
