apiVersion: v1
kind: Service
metadata:
  name: social-media-service
spec:
  type: NodePort
  selector:
    app: social-media-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30007
