apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: social-media-app
spec:
  minReplicas: 2
  maxReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: social-media-app
  metrics:
    - type: Object
      object:
        metric:
          name: http_requests_total
        describedObject:
          apiVersion: v1
          kind: Pod
          name: my-app
        target:
          type: AverageValue
          averageValue: 10
