apiVersion: v1
kind: Service
metadata:
  name: social-media-app-service
spec:
  selector:
    app: social-media-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
