apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: social-media-app
spec:
  minReplicas: 1
  maxReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: social-media-app
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 60
