apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-primary-config
data:
  primary.cnf: |
    [mysqld]
    server-id=1
    log-bin=mysql-bin
    binlog_format=row
    log_bin_trust_function_creators=1
