apiVersion: v1
kind: Service
metadata:
  name: mysql-primary
spec:
  selector:
    app: mysql-primary
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-replica
  labels:
    app: mysql-replica
spec:
  clusterIP: None
  selector:
    app: mysql-replica
  ports:
    - port: 3306
      targetPort: 3306
