apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: "mysql"
  replicas: 3
  template:
    metadata:
      labels:
        app: mysql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
              name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: root-password
            - name: MYSQL_DATABASE
              value: mydb
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          command:
            - bash
            - "-c"
            - |
              # Extract ordinal index from pod name (mysql-0, mysql-1, etc.)
              SERVER_ID=$([[ "$POD_NAME" =~ -([0-9]+)$ ]] && echo $((${BASH_REMATCH[1]} + 1)) || echo 1)
              exec docker-entrypoint.sh mysqld \
                --server-id=$SERVER_ID \
                --log-bin=mysql-bin \
                --binlog-format=ROW \
                --gtid-mode=ON \
                --enforce-gtid-consistency \
                --default-authentication-plugin=mysql_native_password
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d
          readinessProbe:
            exec:
              command:
                - bash
                - "-c"
                - |
                  mysql -u$MYSQL_USER -p$MYSQL_PASSWORD -e 'SELECT 1'
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
      volumes:
        - name: init-scripts
          configMap:
            name: mysql-init-scripts
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
