apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-replica
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
    whenScaled: Delete
  serviceName: mysql-replica
  replicas: 2
  selector:
    matchLabels:
      app: mysql-replica
  template:
    metadata:
      labels:
        app: mysql-replica
    spec:
      initContainers:
        - name: init-replica
          image: mysql:8.0
          command: ["/bin/bash", "/scripts/init-replica.sh"]
          volumeMounts:
            - name: replica-init
              mountPath: /scripts/
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_REPLICATION_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_REPLICATION_PASSWORD
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_REPLICATION_MODE
              value: slave
            - name: MYSQL_MASTER_HOST
              value: mysql-primary
            - name: MYSQL_MASTER_PORT
              value: "3306"
            - name: MYSQL_REPLICATION_USER
              value: replicator
            - name: MYSQL_REPLICATION_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_REPLICATION_PASSWORD
          volumeMounts:
            - name: mysql-config
              mountPath: /etc/mysql/conf.d
            - name: data
              mountPath: /var/lib/mysql
            - name: mysql-init
              mountPath: /docker-entrypoint-initdb.d/
      volumes:
        - name: mysql-config
          configMap:
            name: mysql-replica-config
        - name: mysql-init
          configMap:
            name: mysql-init-script
        - name: replica-init
          configMap:
            name: mysql-replica-init
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
