on:
  pull_request:
    types: [labeled]

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Run only if "bug" label is added
        if: ${{ github.event.label.name == 'bug' }}
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{
            "channel": "#alerts-channel",
            "attachments": [
              {
                "text": ":pull-request: *PR created* " by user  ${{ github.event.pull_request.user.login}}"\n
                        Please review <'${{ github.event.pull_request.html_url' | '${{ github.event.pull_request.html_urlbody }}'>
                "color": "#8B0000",
                "attachment_type": "default"
              }
            ]
          }' "https://hooks.slack.com/services/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"
